on:
  push:

jobs:
  search:
    strategy:
      matrix:
        q: [gpr, g, private]
        prerelease: [false]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: curl "https://nuget.pkg.github.com/jcansdale-test/query?q=${{ matrix.q }}&prerelease=${{ matrix.prerelease }}&semVerLevel=2.0.0" -u token:${{ secrets.READ_PACKAGES_TOKEN }} | jq .
